formatter: "markdown table"
header-from: main.tf
footer-from: ""
sections:
  show: 
    - requirements
    - inputs 
    - outputs

output:
  file: README.md
  mode: inject

# settings:
#   hide-empty: true